/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlks.view;
import java.sql.DriverManager;
import java.sql.SQLException;
import qlks.dao.JDBCconnection;
import qlks.modal.AllRoom;
import qlks.service.AllRoomService;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class EditRoomFrame extends javax.swing.JFrame {

    
    private AllRoom allRoom;
    AllRoomService allRoomService;
    /**
     * Creates new form EditRoom
     */
    
    private java.sql.Connection connection;

    public java.sql.Connection getConnection() {
        return connection;
    }

    public void setConnection(java.sql.Connection conn) {
        this.connection = conn;
    }

    public java.sql.Connection getConnect() throws ClassNotFoundException, SQLException {
        Class.forName(JDBCconnection.driverName);
        connection = DriverManager.getConnection(JDBCconnection.dbURL, JDBCconnection.dbUser, JDBCconnection.dbPass);
        System.out.println("CONNECTTED!");
        return connection;
    }
    
    public EditRoomFrame( String MP) throws ClassNotFoundException, SQLException{
        
        allRoom = new AllRoom();
        allRoomService = new AllRoomService();
        allRoom = allRoomService.getRoomByID(MP);
        
        initComponents();
        
        inputMP.setText(allRoom.getMaPhong());
        inputStatus.setSelectedItem(allRoom.getTinhTrang());
        inputCleanStatus.setSelectedItem(allRoom.getCleanStatus());
        inputBedtype.setSelectedItem(allRoom.getBedType());
        inputPrice.setText(allRoom.getGia());
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputMP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        inputCleanStatus = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        inputBedtype = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        inputPrice = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setText("Trang cập nhật thông tin phòng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 36));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setText("Mã Phòng");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 85, -1));

        inputMP.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        inputMP.setEnabled(false);
        getContentPane().add(inputMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, 167, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setText("Tình trạng");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        inputStatus.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        inputStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống", "Đang thuê" }));
        getContentPane().add(inputStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 167, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setText("Vệ sinh");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 62, -1));

        inputCleanStatus.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        inputCleanStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã vệ sinh", "Bẩn" }));
        getContentPane().add(inputCleanStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 167, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("Loại giường");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 96, -1));

        inputBedtype.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        inputBedtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi" }));
        getContentPane().add(inputBedtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, 167, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel6.setText("Giá");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 72, -1));

        inputPrice.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        getContentPane().add(inputPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, 167, -1));

        btnSubmit.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        btnSubmit.setText("Update");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, 122, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlks/img/room.jpeg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 540, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        try {
            connection = getConnect();
            
            String sql = "update Loai_Phong set tinhTrang = N'"+inputStatus.getSelectedItem()+"' , cleanStatus= N'"+inputCleanStatus.getSelectedItem()+"' , bedType = N'"+inputBedtype.getSelectedItem()+"' , Gia = '"+inputPrice.getText()+"' where MaPhong =N'"+inputMP.getText()+"'";
            
            PreparedStatement preparedStatement = connection.prepareStatement(sql);
            
            int rs = preparedStatement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Sửa thông tin thành công");
            new AllRoomFrame().setVisible(true);
            this.dispose();
            
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> inputBedtype;
    private javax.swing.JComboBox<String> inputCleanStatus;
    private javax.swing.JTextField inputMP;
    private javax.swing.JTextField inputPrice;
    private javax.swing.JComboBox<String> inputStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
